SAFE-Stack/SAFE-template

Content/src/Client/App.fs
RELEASE_NOTES.md

As per https://fable-elmish.github.io/react/browser.html#A-React-SPA

make the Client code even simpler

---

.paket/Paket.Restore.targets
CONTRIBUTING.md
Content/.paket/Paket.Restore.targets
Content/build.fsx
Content/paket.dependencies
Content/paket.lock
Content/src/Client/App.fs
Content/src/Client/paket.references
README.md

Previously "Run" command called "Build", and created webpack production bundle.
Some dependencies updated to match the BookStore.

Added HMR, created separate run target to make it faster

---

Content/src/Client/App.fs

See https://github.com/dotnet/templating/issues/627#issuecomment-296326216

Fix preprocessor directives

---

Content/src/Server/Program.fs

Rename `path` in Server/Program.fs to avoid collision with Suave

---

README.md

Fix links to Bulma templates.
CC: @theimowski

fix bulma links

---

Content/paket.dependencies
Content/src/Server/ServerGiraffe.fs
Content/src/Server/ServerSaturn.fs
Content/src/Server/paket.references

@theimowski can you have a quick look at what I've done in this PR and see if it looks about right? I don't even know how to build the template locally so this is just being done "blind".
When complete, this will fix #49

Add Fable Json serialization to Saturn and Giraffe.

---

Content/src/Server/ServerSaturn.fs

Remove Saturn browser router

---

Content/.gitignore

@theimowski this is rather urgent since I want to describe release scripts in the docs

Add release scripts to gitignore

---

Content/paket.dependencies
Content/src/Client/Client.fs

Don't use Fulma prerelease

---

Content/src/Server/ServerGiraffe.fs
Content/src/Server/ServerSaturn.fs

Fixes #91. @Banashek can you test this version out to confirm?

Always open Microsoft.Extensions.DependencyInjection.

---

Content/src/Server/ServerSaturn.fs

Fix #104 add 'disable_diagnostics' option to saturn application when Fable.Remoting is enabled 

---

Content/build.fsx

Increased timeout for uploading files to the app service

---

Content/src/Client/webpack.config.js

See https://github.com/fable-compiler/Fable/issues/1490

Allow symlinks

---

Content/src/Client/Client.fs

fixes https://github.com/SAFE-Stack/SAFE-template/issues/125

Remove intersperse

---

Content/build.fsx

use FAKE's new CreateProcess API

---

Content/package-lock.json
Content/package.json
Content/yarn.lock

[WIP] Cleanup js deps

---

Content/src/Client/Client.fs
Content/src/Client/paket_noremoting-fulma-noreaction.lock
Content/src/Client/paket_noremoting-fulma-reaction.lock
Content/src/Client/paket_noremoting-nofulma-noreaction.lock
Content/src/Client/paket_noremoting-nofulma-reaction.lock
Content/src/Client/paket_remoting-fulma-noreaction.lock
Content/src/Client/paket_remoting-fulma-reaction.lock
Content/src/Client/paket_remoting-nofulma-noreaction.lock
Content/src/Client/paket_remoting-nofulma-reaction.lock

 Demonstrate usage of `nothing` from Fable.React

---

Content/src/Client/webpack.config.js

Webpack: set terser minifier configuration compress.inline to false

---

Content/src/Client/Client.fs

Remove bulma burgers from fulma layouts

---

tests/Tests.fs

[WIP] Tests: killProcessTree - do nothing if process is not running

---

Content/src/Server/ServerSaturn.fs

A small simplification that takes advantage of Saturn's `use_json_serializer` application command.

Take advantage of use_json_serializer.

---

Content/src/Server/Server.fsproj
Content/src/Shared/Shared.fsproj

Add Shared.fsproj

---

Content/src/Client/Client.fs

fixes https://github.com/SAFE-Stack/SAFE-template/issues/203
----------
After #199:
Should actually be:

Fontawesome small changes

---

Content/.template.config/template.json
Content/SAFE.Template.sln
Content/src/Client/Client.fsproj
Content/src/Server/Server.fsproj

Fixes #260. I added paket files to the solution and project files plus other files that might be useful.

Move .sln to the root directory and add files

---

build.fsx

Use correct path separator and don't fail on paths with spaces

---

Content/build.fsx

Supports supplying tenant id as per latest docs etc.

Support for tenantId.

---

Content/.vscode/launch.json

This fixes F5 full stack debugging in VSCode.

Fix program launch to correct netcoreapp

---

Content/package-lock.json
Content/package.json
Content/yarn.lock

Update npm dependencies

---

.config/dotnet-tools.json
.travis.yml
CONTRIBUTING.md

Use FAKE and Paket local tools in template project

---

Content/src/Server/ServerSaturn.fs

As a general theme we should not use >> in the template - I think this makes it easier for people to understand what's going on

remove use of >>

---

Content/README.md

`mono` is not required anymore.

Remove outdated pre-requisites

---

Content/src/Client/App.fs
Content/src/Client/Client.fsproj
Content/src/Client/Index.fs
Content/src/Client/package-lock.default.json
Content/src/Client/package-lock.minimal.json
Content/src/Client/package.default.json
Content/src/Client/package.minimal.json
Content/src/Client/webpack.tests.config.js
Content/tests/Client/Client.Tests.fs
Content/tests/Client/index.html

Fix tests and update npm dependencies

---

Content/default/.paket/Paket.Restore.targets
Content/default/package-lock.json
Content/default/package.json
Content/minimal/package-lock.json
Content/minimal/package.json
SAFE.Template.proj

Pin selfsigned package

---

Content/default/package-lock.json
Content/default/package.json
Content/minimal/package-lock.json
Content/minimal/package.json

- ini: cherry picked dependabot's commits
- object-path: seems not supported by dependabot. Manually updated resolve-url-loader

Fix vulnerabilities

---

tests/Tests.fs

There were two issues preventing tests working on windows.
The first is `pgrep`, used for getting child process to kill the process tree. Fixed using `wmic` when on windows.
The second is the path to `npm`. The fix code to locate it is copied from fake until we address #219

Make Tests work on windows

---

Content/default/Build.fs
Content/default/package-lock.json
Content/default/package.json
Content/default/webpack.config.js
Content/default/webpack.tests.config.js

Basic support for source maps

---

Content/default/src/Server/Server.fs
Content/minimal/src/Server/Server.fs

Fixes localhost proxy for node 17, discussion https://github.com/SAFE-Stack/SAFE-template/pull/485#discussion_r760543025

Listen on all interfaces including ipv6

---

Content/default/Build.fs
Content/default/src/Server/Properties/launchSettings.json
Content/default/src/Server/Server.fs
Content/default/webpack.config.js
Content/minimal/src/Server/Properties/launchSettings.json
Content/minimal/src/Server/Server.fs
Content/minimal/webpack.config.js

Changes to allow Linux Azure App Service

---

Content/default/src/Server/Properties/launchSettings.json
Content/minimal/src/Server/Properties/launchSettings.json

Fixes the issue reported by @theimowski in #528

Fix dev-time server URL (https -> http)

---

Content/default/src/Server/Properties/launchSettings.json
Content/minimal/src/Server/Properties/launchSettings.json
tests/Main.fs
tests/Tests.fs

To be able to catch errors related to Server HTTP requests

Test HTTP GET request against server api

---

Content/default/.vscode/extensions.json

Remove deprecated extension recommendation

---

Content/default/Build.fs
Content/default/Helpers.fs

#551 Refactor: use CreateProcess.fromRawCommand

---

Content/default/.config/dotnet-tools.json

Update Fable to 3.7.22

---

Content/default/.editorconfig
Content/default/Build.fs
Content/default/Helpers.fs
Content/default/src/Client/Index.fs
Content/default/src/Server/Server.fs
Content/default/src/Shared/Shared.fs
Content/default/tests/Client/Client.Tests.fs
Content/default/tests/Server/Server.Tests.fs
Content/default/tests/Shared/Shared.Tests.fs

- Update fantomas config to format brackets
- Format the files
- Change className to classes for styles so formatting is nicer

Update fantomas config and format files

---

Content/default/.config/dotnet-tools.json
Content/minimal/.config/dotnet-tools.json

Update fable
* Ran into issue where did not compile F# 8 nested record update and replace syntax; newer fable version fixes this

update fable version

---

Content/default/package-lock.json
Content/default/package.json
Content/default/src/Client/App.fs
Content/default/src/Client/index.html
Content/minimal/src/Client/index.html

* Remove elmish debugger, as it depends on un-maintained package https://github.com/zalmoxisus/remotedev
*  Resolves #602

Remove Elmish.Debugger 

---

.github/workflows/release.yml
Build.fs

* automatically write release notes after release

Automated relase note file update

---

Content/default/src/Client/Index.fs

what changed?: improve the ui for todo app
why?: not very ux friendly. after react series blog post being published there is a need to give a good first impression to those testing SAFE stack for the first time.
effect?: tailwind changes
There were quite a lot of problems with the old UI. 
- Background image bled into the text on the todos list component
- text colour choice for title and text within todos list component was hard to read with backgruonds that had more blackish colours.
- didn't look very professional/modern
- not mobile responsive
all of these have been resolved with this PR
desktop:
mobile:

[feat]: Improved UI for todo app to enhance user experience and first impressions
