README.md

I guess it was called _App.fs_ before. However currently by default SAFE template creates there _Client.fs_ file.

Updated README (synchronized a file name)

---

Content/src/Server/ServerGiraffe.fs

Fixed [Issue42](https://github.com/SAFE-Stack/SAFE-template/issues/42) when Giraffe Server fails with NRE,  cause hasnt `ConfigureServices` section in Server.fs

fixed template with Giraffe Server

---

Content/src/Server/ServerSaturn.fs

"/index.html" resolves to the machine root. "index.html" combined with clientPath works as expected.

Fixes path to index.html in Saturn template

---

Content/paket.dependencies
Content/src/Client/Client.fs
Content/src/Server/ServerGiraffe.fs
Content/src/Server/ServerSaturn.fs
Content/src/Server/ServerSuave.fs

Update server adapters to 2.6 / client to 2.4, these are most stable and most heavily tested versions. 
Use latest `remoting` API to create the handlers in accordance with the [docs](https://zaid-ajaj.github.io/Fable.Remoting/), (still backwards compatible)   
I only tested the template with Suave server locally.
Suggestion: 
- Use default remoting implementation without `Route.builder`?
- rename `Route.builder` to `Route.prefixWithApi`?

Update Remoting, use latest API

---

Content/src/Client/index.html

I had to set the charset to utf8 in order to display `str “äöü“` correctly, otherwise it fallbacks to ascii?! which looks quite ugly ;-)

Add charset attribute to index.html

---

Content/build.fsx

Caught this while looking at @isaacabraham's Application Insights PR. Verified locally. Works on my machine. ;)

Fixes filepath for Unix-based systems

---

Content/src/Server/ServerSuave.fs

Running `dotnet new SAFE --Server suave` adds app insights web part to main Suave web part which doesn't work because that only works if the `Deploy = "azure"`. This PR fixes it. 
Also, a couple of names: `init => webApi` and `webPart => webApp` because "webApi is part of webApp" makes a bit more sense than "init is part of webPart" 
Tested locally, but messed up my branch so I just copy pasted it here ;)

Enable AppInsights only if Deploy = 'azure' on Suave server

---

Content/src/Client/Client.fs

⚠️ I needed to remove the following line from `paket.dependencies` to make the template work.
```
//#if (Deploy == "azure")
nuget Microsoft.Azure.Management.ResourceManager.Fluent 1.4.1
github CompositionalIT/fshelpers src/FsHelpers/ArmHelper/ArmHelper.fs
//#endif
```
Otherwise, the template engine was complaining about `srcOffset` being invalid. Please test in your PR before publishing a new version.

[WIP] Update to latest Fulma

---

Content/.template.config/template.json
Content/build.fsx
Content/paket.dependencies
Content/src/Client/Client.fs
Content/src/Client/paket.references
Content/src/Client/public/index.html
Content/src/Server/Server.fsproj
Content/src/Server/ServerGiraffe.fs
Content/src/Server/ServerSaturn.fs
Content/src/Server/ServerSuave.fs
Content/src/Server/paket.references
Content/src/Shared/Shared.fs

lowercased parameters and updated sources

---

Content/src/Server/ServerSaturn.fs

Now that Saturn 0.5.0 has been released with built-in default static pages, we can remove it from the SAFE template.

Remove configure app from Saturn.

---

Content/build.fsx

I created the app in the dir: _C:\Users\peter\Desktop\dev life\SAFE_.
Bundle target produces an unclear exception and MSBuild error: "_Only one project can be specified_".
Escaping strings fixes this.

Solidified Bundle target

---

Content/paket.dependencies

This fixes #116, Fable.Remoting had an [upgrade](https://zaid-ajaj.github.io/Fable.Remoting/src/change-log.html) and it seems that dependencies with the breaking changes are being resolved instead of the compatible dependencies
I will be able to upgrade the template to latest remoting version very soon, for now, this should work.

Pin compatible Remoting.Server version, fixes #116

---

Content/README.md

As a user of the SAFE template I might want to have an initial Readme which tells me how to run/deploy the newly created application. I don't know how much value it adds as people learning about the template most likely do so from the SAFE documentation site but at least for other contributors or people who just find the repo in source control it could be helpful.

Add README.md file to SAFE Template content

---

Content/src/Client/webpack.config.js

Added more comments to the `webpack.config.js` file. I also removed the CONFIG object and embedded it directly into the configuration - I'm not sure if this is better or worse, happy to revert that, but for me as a non-webpack person it means one less object to reason about in the file.
Also renamed the server proxy port to `SERVER_PROXY_PORT ` - otherwise it could be confusing for people using different web servers. Theoretically this is a breaking change so I would like to get this in before v1.

Add more comments in webpack.js

---

Content/.template.config/template.json
Content/app.yaml
Content/build.fsx
Content/src/Server/ServerGiraffe.fs
Content/src/Server/ServerSaturn.fs
Content/src/Server/ServerSuave.fs
README.md

Add support for google cloud appengine.
To really test you need a gcp project and gcloud installed. For now the same Dockerfile as for docker deploy is used, it might make sense to change to a dedicated one for gcp later for easier integration with other gcp services. 
To do a test deploy run the following two commands:
```
dotnet new SAFE --deploy gcp-appengine
fake build --target deploy
```
Deploy of appengine flex apps is not super fast, but as long as there are no errors it should work.

Add GCP appengine support

---

.paket/Paket.Restore.targets
Content/.template.config/template.json
Content/build.fsx
Content/paket.dependencies

Fixes: https://github.com/SAFE-Stack/SAFE-template/issues/208
Docs: https://github.com/SAFE-Stack/docs/pull/91
Adds support for kubernetes in general and Google Cloud Kubernetes Engine in particular. 
The PR assumes two tools are pre-installed:
* `gcloud` - cli tool to interact with gcp
* `kubectl` - cli tool to interact with kubernetes
Given the above is installed and that you have a gcp project and gke cluster running. You can test this out by running:
```
dotnet new SAFE --deploy gcp-kubernetes
fake run build.fsx -t Deploy
```
Again, this serves as a way to getting started and will suffice for smaller apps.

Add GCP GKE support

---

Content/paket.dependencies

If I understand @matthid correctly, then this is no longer needed

Remove FAKE issue warning

---

Content/.paket/Paket.Restore.targets

Using paket global, a `dotnet new safe` fails, I think because paket restore targets are out of date. I've updated them using the latest one that is generated by paket and this *seems* to fix it.
Can someone else test locally though please :-)

Fix initial build failure

---

Content/build.fsx

Fixes an issue where the gcloud  command is not found on Windows.
Followed the same pattern that is applied to other tools.

Fix gcloud tool name on Windows

---

Content/.template.config/template.json
Content/build.fsx
Content/src/Server/ServerGiraffe.fs
Content/src/Server/ServerSaturn.fs
Content/src/Server/ServerSuave.fs
tests/Tests.fs

There is a link to `https://github.com/SAFE-Stack/SAFE-buildpack`. The working buildpack for testing is `https://github.com/Nhowka/dotnetcore-buildpack#SAFETEST` instead.
After the login on `heroku-cli`, using `fake build -t configure` and `fake build -t deploy` should be enough to start a template made with `dotnet new SAFE --deploy heroku`.
As the FAKE script will run on the heroku machine too, I repeat the `herokuTool` and `gitTool` inside the targets so it won't raise an exception for not finding them.
It should be used instead of #137 as it is very outdated.

[WIP] Support heroku

---

Content/src/Server/ServerGiraffe.fs

Got a bug in a private repo that took me forever to debug down through Thoth not wanting to run the extra encoders/decoders given to the `ThothSerializer`. The error I got was:
```txt
09:24:47 [Error] () Connection id ""0HLMNEG9T1D5V"", Request id ""0HLMNEG9T1D5V:00000001"": An unhandled exception was thrown by the application.
System.AggregateException: One or more errors occurred. (Could not determine JSON object type for type Shared.Model+Msg+HomeMsg.) ---> System.ArgumentException: Could not determine JSON object type for type Shared.Model+Msg+HomeMsg.
at Newtonsoft.Json.Linq.JValue.GetValueType(Nullable`1 current, Object value)
at Thoth.Json.Net.Encode.autoEncoder@454-14.Invoke(Object v)
at Thoth.Json.Giraffe.ThothSerializer.Giraffe-Serialization-Json-IJsonSerializer-SerializeToBytes[ …
```

Be explicit that the returned object should be JSON

---

Content/src/Client/Client.fsproj

this makes the ionide aware of the fact that this is a fable project.
This is needed if `#if FABLE_COMPILER` directives that are sometimes needed for SSR - especially when you want to have Thoth.Fetch in one end and Thoth.Net on the other.
/cc @Krzysztof-Cieslak @isaacabraham @MangelMaxime

Set Fable variable on client project

---

Content/build.fsx

I don't think this is still needed.
I think I added it long time ago in bookstorish project because fable was a dotnet tool that we needed to restore explicitly.

no need to restore client

---

Content/.gitignore

Ionide builds up a symbol cache which it stores locally, we don't need this in source control. Given that we encourage people to use Ionide in VS we should ensure people don't encounter any unnecessary friction.

Add .ionide to gitignore

---

Content/build.fsx

Instead of specifying the `runTool` working directory as `"."`, which might be any directory depending on where the build script was run from, we should use `__SOURCE_DIRECTORY__` which will always be consistent.

Fix runTool working directory

---

Content/src/Client/Client.fs

Fix indentation to be in line with [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting).

Fix indentation for DU definition and pattern match

---

Content/src/Client/style.scss

The Events / Inventory Search boxes were not centered properly
Before:
After:

Fulma Admin template small position fix

---

Content/.vscode/extensions.json

The extension for csharp has changed publisher from ms-vscode to ms-dotnettools 
https://github.com/OmniSharp/omnisharp-vscode/pull/3610

Update publisher for vscode csharp extension

---

.travis.yml
Content/.config/dotnet-tools.json
Content/.devcontainer/Dockerfile
Content/.vscode/tasks.json
Content/README.md
tests/Tests.fs

This removes FAKE and Paket as a global dependencies, using dotnet local tools instead.
- Tests don't work for me locally before or after my changes, possibly due to environmental issues.
- I've not tested the Dockerfile. I don't really use docker.
I haven't moved away from global tools for the SAFE-template project itself, but we should do that as the next step, unless @theimowski is doing this for v2 anyway.

Use FAKE and Paket local tools in template output

---

build.fsx

In the dev server proxy, it proxies requests from `/api/*` to the server.
This PR fixes it so that it only proxies requests starting with `/api/` instead of all starting with `/api`.
See https://github.com/webpack/webpack-dev-server/issues/2454 for details

Fix devServerProxy context paths

---

Content/.vscode/launch.json

This sets the working directory in the vscode launch config for debugging the server.
Fixes #239

Set working directory for debugging server

---

Content/src/Client/webpack.default.config.js

Noticed that #341 didn't make it into one of the webpack configs in v2_minimal

Fix devServerProxy context paths in V2 minimal

---

Content/app.yaml

Health check configuration has changed and initial deployment to Google App Engine fails currently. Related:
https://cloud.google.com/appengine/docs/flexible/dotnet/migrating-to-split-health-checks
Sample configuration file no longer has health_check section https://cloud.google.com/appengine/docs/flexible/dotnet/configuring-your-app-with-app-yaml

Remove legacy health checks entry from Google Cloud App Engine app.yaml

---

Content/build.fsx

We don't need to do: `if Environment.isUnix then "npm" else "npm.cmd"`

Simplify FAKE script a bit

---

Content/src/Client/Client.fs

Whenever we add more than a handful of input fields to a SAFE project we see a bug where any input field change makes the cursor jump to the end of the field. Using `Program.withReactSynchronous` instead of `Program.withReactBatched` fixes this.

Use Program.withReactSynchronous to avoid input focus bug

---

Content/src/Client/Index.fs

I think we should avoid the arrow syntax as many people aren't aware that it exists and it doesn't play nicely with implicit yield. If you put another item adjacent to it you have to use the yield keyword.

Use `do` instead of `->` when yielding todos

---

README.md

https://saturnframework.github.io/docs/ leads to 404, I assume the intended info is found at https://saturnframework.org/ instead

Fix link for Saturn framework

---

Content/default/README.md
Content/minimal/README.md

https://saturnframework.org/docs returns a 404

Fixed link for Saturn documentation

---

Content/default/Build.fs
Content/default/SAFE.App.sln

While working on SAFE apps I often find that Fable gets into a bad state with cached JS files which isn't fixed by restarting the build script, so I always add this command to delete all `*.fs.js` files.

Add dotnet fable clean

---

Content/default/tests/Server/Server.Tests.fs

This PR replaces the server test's entry point with the recommended function. 
Expecto's `runTests` is deprecated.
https://github.com/haf/expecto#runtests.

Replace deprecated Expecto entrypoint

---

Content/default/src/Client/index.html
Content/minimal/src/Client/index.html

Included the following meta tag in index.html for both templates
```
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```
Before
After

Added meta tag for viewport to help with mobile responsiveness

---

Content/default/.config/dotnet-tools.json

Fixes #463. This also updates the other dotnet tools in the repository to latest versions:
* Paket 6 moves out of RC
* Minor update to Fantomas
* Patch update to Fable

Add Femto tool

---

Content/default/paket.lock

Fixes #464, Fixes #461. This enables error checking on running the FAKE Deploy step if the name of the app leads to the template creating an invalid web app name, which will be rejected by Azure.

Update Farmer to 1.6.12

---

Content/default/src/Server/Server.fs

Small reformatting but also move from a class to a module and let-bound functions.

Rework default Server.fs - move to a module

---

Content/default/tests/Server/Server.Tests.fs

Currently the master branch has broken tests as they still use the old class that has been removed in #465. This PR fixes that.

Update Server tests to use module that replaced class

---

Content/default/tests/Client/Client.Tests.fs

In line 15, actual value is model.Todos.Length , expected value is 1.
In line 16, actual value is model.Todos.[0] , expected value is newTodo.
Both origin code  are reverse parameters.

Fix Client.Test.fs Expect.equal parameters order

---

Content/default/global.json
Content/minimal/global.json

It looks like the sdk version needs a band/feature version to roll forward *from*

Fixes .net sdk selection issue discussed in #533

---

Content/default/package-lock.json
Content/default/package.json
Content/minimal/package-lock.json
Content/minimal/package.json

The templates work with node v18 (current latest LTS), so we could allow it.

Update package.json files to allow node 18 (as well as 16)

---

Content/default/package-lock.json
Content/default/package.json
Content/minimal/package-lock.json
Content/minimal/package.json

Build currently fails with:
```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: undefined
npm ERR! notsup Not compatible with your version of node/npm: undefined
npm ERR! notsup Required: {"node":"~16 || ~18","npm":"~8"}
npm ERR! notsup Actual:   {"npm":"9.5.1","node":"v18.16.0"}
```
https://compositional-it.visualstudio.com/SAFE%20Template/_build/results?buildId=13090&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5

Fix failing build because of NPM version

---

Content/default/Build.fs

Only just noticed that the -r created a folder in src as I ran dotnet run format yesterday ;) 
Should run on Build.fs also

removed -r switch from fantomas/run at root in build.fs

---

Content/default/src/Client/Index.fs
Content/default/src/Server/Server.fs

Pretty self explanatory. Most IDEs do sufficiently well to provide annotations hints that they aren't required e.g. in VSCode with Ionide:

Remove unnecessary type annotations on main files.

---

Build.fs

- "dotnet nuget push..." instead of "dotnet new push..."
- Publish from the package containing the nupkgs

Fix build script failing on publish because of incorrect dotnet command

---

Build.fsproj
Content/default/Build.fsproj
Content/default/README.md

By adding a target in Build.fsproj to run `dotnet tool restore`, we can remove the step that requires users to do it manually.
Should we go ahead with this? Discussion welcome.

Do `dotnet tool restore` automatically in build target

---

Content/default/tests/Client/Client.Tests.fs

Fix bug issue #615
Helping Copilot to explain the fix, **ex-post**.
> giuliohome: explain why adding line "let model, _ = update (LoadTodos (Finished [])) model" fix a bug so that the test does not fail now
>GitHub Copilot: The line `let model, _ = update (LoadTodos (Finished [])) model` is loading an empty list of todos into the model. This is likely fixing a bug where the model's todo list was not initialized properly, causing the test to fail.
> In the previous state, the model might have been in an uninitialized state or contained some stale data. By explicitly loading an empty list of todos, it ensures that the model is in a known and clean state before the test starts to add a new todo. This makes the test more reliable and predictable, as it's not affected by the previous state of …

Fix bug issue #615 in Client.Tests.fs

---

Content/default/Build.fs

addresses #618
* NPM ci only installs packages according to package.json and package.lock, failing if they don't line up. CI is faster and will prevent unexpected changes to package.lock until the developer explicitly uses NPM install

Use npm ci in the build script so package.lock cannot get updated there

---

Build.fs
Content/default/Build.fs
Content/default/Helpers.fs
Content/default/README.md
Content/default/package-lock.json
Content/default/package.json
Content/default/tests/Client/package.json
azure-pipelines.yml

* Add build action in default project to run tests one-off using mocha test runner (instead of in browser)
* Add build action in template build script to run these tests

Run project tests as part of template testing

---

Content/default/src/Client/Index.fs
Content/default/src/Server/Server.fs
Content/default/src/Shared/Shared.fs
Content/default/tests/Client/Client.Tests.fs

Addresses #615 in a more conclusive manner:
* Test failed because it lacked loading the initial data; because the added todo was mapped into a RemoteData type, data disappeared quietly when that RemoteData object was not in the Finished state yet.
* Solution: Make the API return the full todo list, so you can fully replace the todo list after an update

Change the api to return full TODO list after adding todo

---

Content/default/Build.fs

* Remove dotnet restore action before running the watcher
* instead of building just the shared path, build the full solution
* Use `no-restore` when running server tests
* restore full solution before running any tests
addresses what is left of #626 after partial fix in #634

Fix error caused by restore on running tests + build solution before run, instead of just restore
